### PR TITLE
added delete button

### PR DESCRIPTION
**Pull request by Jeffchiucp**
issue #28

### CODE REVIEW

**Comment by Jeffchiucp** [comment]
i added the delete button and delete routes #28

**Comment by Jeffchiucp** [comment]
please review and approve the changes. Thanks. @anselb

**Comment by Jeffchiucp** [comment]
need to added jQuery when we click on the Deletion Button.

**Comment by JeffChiu2009** [comment]
Need to add jQuery codes to fix this push!

**Pull request merged**
